language: php
php:
  - 7.3

sudo: false
dist: trusty

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --dev --no-interaction --prefer-dist

script:
  - ./run_bench.sh > /dev/null

after_script:
 - cat ./report-total.md
 - cat ./report-draft-04.md
 - cat ./report-draft-06.md
 - cat ./report-draft-07.md
 - cat ./report-ajv.md
